"""
Django settings for test_project project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from datetime import timedelta
from django.conf.global_settings import DATETIME_INPUT_FORMATS
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xxx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'PMIS.apps.PmisConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'corsheaders',
    'webpack_loader',
    'rosetta',
    'rest_framework',
    'rest_framework_filters',
    'crispy_forms',    
    'WEB_PMIS',
    'DataBase_MPMS',
    'DataBase_PMSDSCSYS',
    'datatableview',
    'DataBase_VCAsia_db',
    'BaseProject',
    'BaseApp',
    'PMISLooper',
    'DevPlat',
    'LocaleApp',
    'FlowChartApp',
    'BonusApp',
    'BaseReportApp',
    'ScheduleApp',
    'ChatwithAi_app',
    'SystemBugRpt_app',
    'Notification_app',
    'ProjectManagement_app',
    'Authorization_app.apps.AuthorizationAppConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'BaseApp.library.middleware.LogPortMiddleware.LogPortMiddleware'
]

ROOT_URLCONF = 'WEB_PMIS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'WEB_PMIS.tools.context_processors.set_global_parameters'
            ],
            'libraries':{
                "customer_filter":"BaseProject.templatetags.customer_filter",
                "md5url":"BaseApp.library.templatetags.md5url",
            },
        },
    },
]

WSGI_APPLICATION = 'WEB_PMIS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASE_ROUTERS = ['BaseApp.library.sys_objs.DataBase_Router.DataBaseRouter']
DATABASE_MAPPING = {
    "DataBase_MPMS":"MPMS",
    "DataBase_PMSDSCSYS":"PMSDSCSYS",
    "Sys_DSCSYS":"PMSDSCSYS",
    "DataBase_VCAsia_db":"VCAsia_db",
    "ScheduleApp":"MPMS",
    "DataDictionaryDSCSYS":"DataDictionaryDSCSYS",
    "ChatwithAi_app":"MPMS",
    "Notification_app":"MPMS",
    "ProjectManagement_app":"MPMS",
    'Authorization_app':"MPMS"
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'OPTIONS': {
            'timeout': 30,
        }        
    },
    'MPMS': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'M_PMS',
        # 'USER': 'sa',
        # 'PASSWORD': 'Adminsing123',
        # 'HOST': '222.118.20.236',
        'USER': 'dbname',
        'PASSWORD': 'access',
        'HOST': '192.168.2.83',
        'PORT': '1433',
        #'CONN_MAX_AGE':60,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params':'sendStringParametersAsUnicode=false;MultipleActiveResultSets=false'
        },
    },
    'PMSDSCSYS': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'PMSDSCSYS',
        'USER': 'dbname',
        'PASSWORD': 'access',
        'HOST': '222.118.20.236',
        'PORT': '1433',
        #'CONN_MAX_AGE':60,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params':'sendStringParametersAsUnicode=false;MultipleActiveResultSets=false'
        },
    },        
    'DataDictionaryDSCSYS': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'DSCSYS',
        'USER': 'dbname',
        'PASSWORD': 'access',
        'HOST': '222.118.20.108',
        'PORT': '1433',
        #'CONN_MAX_AGE':60,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params':'sendStringParametersAsUnicode=false;MultipleActiveResultSets=false'
        },
    },            
    'VCAsia_db': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'VCAsia_db',
        'USER': 'dbname',
        'PASSWORD': 'access',
        # 'HOST': '192.168.2.83',
        'HOST': '222.118.20.236',
        'PORT': '1433',
        #'CONN_MAX_AGE':60,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params':'sendStringParametersAsUnicode=false'
        },
    },    
}


DATABASE_CONNECTION_POOLING=True

CACHES = {
    # 'default': {
    #     'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',  # 指定緩存使用的引擎，這是內存緩存
    #     'LOCATION': 'unique-snowflake', #給緩存放置的內存區設置一個名字
    #     'TIMEOUT': 600 #默認緩存超時時間，None不超時，單位為秒
    # }
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "KEY_PREFIX":"WEBPMIS_" if not DEBUG else "WEBPMIS_DEBUG_",
        'TIMEOUT': 600, #默認緩存超時時間，None不超時，單位為秒
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            ##"PASSWORD": '',  ##redis服務器的密碼
            "SOCKET_CONNECT_TIMEOUT": 5,  # socket 建立連接超時設置
            "SOCKET_TIMEOUT": 5,   #連接建立後讀寫操作超時設置
            # "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",  # 是否壓縮
            "CONNECTION_POOL_KWARGS": {"max_connections": 100
            #,"decode_responses":True
            },  # 設置連接池的最大連接數
            #"SERIALIZER": "django_redis.serializers.json.JSONSerializer",  # 默認使用pickle序列化，這裏設置為json, 測試發現有問題，所以暫時不用
        }
    }
}

CACHE_MIDDLEWARE_ALIAS = "default"          # 用於存儲的緩存別名
CACHE_MIDDLEWARE_SECONDS = 600       # 緩存多長時間過期
CACHE_MIDDLEWARE_KEY_PREFIX = "WEBPMIS_" if not DEBUG else "WEBPMIS_DEBUG_"     # 前綴

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',
    ),     
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_METADATA_CLASS': 'WEB_PMIS.sys_objs.AllowOptionsMetadata.AllowOptionsMetadata',
    #'DEFAULT_METADATA_CLASS': 'Rest_app.sys_objs.AllowOptionsMetadata.AllowOptionsMetadata',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',
    #'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_FILTER_BACKENDS':['rest_framework_filters.backends.RestFrameworkFilterBackend','WEB_PMIS.sys_objs.CustomDatatablesFilterBackend.CustomDatatablesFilterBackend'],
    #'DEFAULT_FILTER_BACKENDS': ['rest_framework_filters.backends.RestFrameworkFilterBackend'],
    'PAGE_SIZE': 30   
}

# 人事系統數據庫配置
EMP_SERVER = '192.168.2.200'
EMPDB_USER = 'dbname'
EMPDB_PASSWORD = 'sqlsinghc'
EMPDB_NAME = 'shingwai_db'

#syl 20230818
VC220_REST_API_SERVER = "http://192.168.2.83:8042" #RestApi配置 真實配置
#VC220_REST_API_SERVER = "http://222.118.20.236:8050" #RestApi配置 syl 測試配置
VC220_REST_API_USERNAME = 'hb' #RestApi配置 syl 20230818
VC220_REST_API_PASSWORD = 'hb11' #RestApi配置 syl 20230818


SO_SERVERS = {
    'VC220':'http://222.118.20.236:8050',
}

RESTAPI_ENDPOINT = {
    ##標準格式, method不寫時,默認為get exclude不寫時表示沒有哪個服務需要排除
    # 'dashboard_sale_analysis':{'url':'/dashboard_sale_analysis/','method':'get', 'exclude':['HK']} 
}

AUTH_USERNAME = 'hb'
AUTH_PASSWORD = 'hb11'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""
AUTHENTICATION_BACKENDS = (
    'PMIS.backends.UserBackend.UserBackend',
    'django.contrib.auth.backends.ModelBackend',
)
"""

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

#默認語言
LANGUAGE_CODE = 'en'

#設置I18n和L10N為True
USE_I18N = True
USE_L10N = True

#指定支持語言, 只支持繁簡英文
LANGUAGES = (
    ('en', _('English')),
    ('zh-hans', _('Simplified Chinese')),
    ('zh-hant', _('Traditional Chinese')),
)

#用於存放django.po和django.mo編譯過的翻譯文件
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'WEB_PMIS/locale'),
)
#指定服務器加載翻譯後的mo文件
ROSETTA_WSGI_AUTO_RELOAD=True
ROSETTA_UWSGI_AUTO_RELOAD=True

TIME_ZONE = 'UTC'

USE_TZ = False

FORMAT_MODULE_PATH = [
    'LocaleApp.formats',
]
DATETIME_INPUT_FORMATS += ('%Y-%m-%dT%H:%M:%S.%f','%Y-%m-%dT%H:%M:%S','%Y-%m-%dT%H:%M')
TIME_ZONE = 'Asia/Shanghai'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/home/deployment/ProductEnv/WEB_PMIS/static'
#STATICFILES_STORAGE = 'BaseApp.library.sys_objs.CustomStorage.IgnoreMissingManifestStaticFilesStorage' #生成靜態文件對應的hash版本文件
X_FRAME_OPTIONS ='ALLOWALL'

#跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

# settings.py
AUTHORIZATION = {
    'AUTH_USER_MODEL': 'DataBase_MPMS.Users', #默認為auth.user
    'PASSWORD_ENCRYPTION': True, #默認為False
}

STATICFILES_DIRS = (
       os.path.join(BASE_DIR,'static'),
    )
TEMPLATE_STRING_IF_INVALID = "Invalid String"

MAIN_PAGE = {'all':'WEB_PMIS/main.html'}

LOGIN_URL = '/looper/login_page'
CSRF_FAILURE_VIEW = 'WEB_PMIS.views.csrf_failure'
SESSION_COOKIE_NAME = "sessionid_" + ROOT_URLCONF.split(".")[0]
CSRF_COOKIE_NAME = "csrftoken_" + ROOT_URLCONF.split(".")[0]
WEBPACK_LOADER = {
    'DEFAULT': {
    'CACHE': not DEBUG,
    'BUNDLE_DIR_NAME':'',
    'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
    'POLL_INTERVAL': 0.1,
    'IGNORE': [r'.+\.hot-update.js', r'.+\.map'],
    }
}

BASE_LOG_DIR = os.path.join(BASE_DIR, "log")
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} SQL:{sql} {duration} params:{params}',
            'style': '{',
        },
        # 详细的日志格式
        'standard': {
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d]'
                      '[%(levelname)s][%(message)s]'
        },        
        # 简单的日志格式
        'simple': {
            'format': '[%(levelname)s][%(asctime)s][%(filename)s:%(lineno)d]%(message)s'
        }        
    },    
    # 過濾器
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },    
    'handlers': {
        'console':{
            'level':'DEBUG',
            'filters': ['require_debug_true'],  # 只有在Django debug为True时才在屏幕打印日志            
            'class':'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 默认的
        'default': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': os.path.join(BASE_LOG_DIR, "WEB_PMIS_info.log"),  # 日志文件
            'maxBytes': 1024 * 1024 * 50,  # 日志大小 50M
            'backupCount': 3,  # 最多备份几个
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        # 专门用来记错误日志
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': os.path.join(BASE_LOG_DIR, "WEB_PMIS_err.log"),  # 日志文件
            'maxBytes': 1024 * 1024 * 50,  # 日志大小 50M
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        }        
    },
    'loggers': {
        # 默认的logger应用如下配置
        '': {
            'handlers': ['default', 'console', 'error'],  # 上线之后可以把'console'移除
            'level': 'INFO',
            'propagate': True,  # 向不向更高级别的logger传递
        },        
        'django.db.backends': {
            'handlers': ['default', 'console', 'error'],  # 上线之后可以把'console'移除
            'propagate': False,
            'level':'DEBUG',
        },
    }
}

SYS_ID="WEBPMIS"
SYS_DASHBOARD_TYPE = 'Looper_Dashboard'
SYS_DASHBOARD_STAFF_PAST_QUERY_ID = 'Staff_Past_Query_Id'
FORUM_BASE_URL = 'http://121.13.252.164:8010/Forum'
##FORUM_BASE_URL = 'http://222.118.20.236:8003/Forum'
FORUM_LOGIN_URL = FORUM_BASE_URL + "/user/login" 
FORUM_POST_TOPIC = FORUM_BASE_URL + "/topic/new_topic"
FORUM_SHOW_TOPIC = FORUM_BASE_URL + "/topic/article?topicsNo={0}"
FORUM_POST_CATEGORY = '20200226007' #PMIS
CACHES_NAME_PARTUSERNAME = "PartUserNames" ##電腦部用戶
CACHES_NAME_GOALPERIODS = "GoalPeriods" ##Goal master中的前幾個Periods
CACHES_NAME_ALLRRECORDID = "AllRecordId" ##所有RecordID
CACHES_NAME_TASKTYPELIST = "TaskTypeList"
CACHES_NAME_GLOBAL_TYPELIST = "GlobalTypeList"

BONUS_SERVICE_URL = 'http://192.168.2.1/InterfaceService/xfire/services/BonusService?wsdl'
BONUS_ANALYSIS_URL='http://222.118.20.236:8000/bonus/bonus_analysis' 
#BONUS_ANALYSIS_URL='http://222.118.20.236:8010/bonus/bonus_analysis' 


SESSION_USERNAME='username'

PUSH_URL="http://222.118.20.236:8020/push"

ELASTICSERVERS_SERVERNAME="http://222.118.20.235:9200"
ELASTICSERVERS_ELASTICINDEXNAME="pmstechnic"
ELASTICSERVERS_ELASTICDOCINDEXNAME="pmsdoc"
ELASTICSERVERS_USERNAME="xxx"
ELASTICSERVERS_PASSWORD="xxx"

SIMPLE_ERP_URL="http://192.168.2.111:8888/SimpleErp"
WEBPMS_URL = "http://192.168.2.111:8888/WEBPMS"
#WEBPMS_URL = "http://192.168.2.92:8080/WEBPMS"
DEVELOPMENT = True

EMP_REST_API_SERVERS = {
    'HC':'http://192.168.2.83:8017',   
    'YM':'http://192.168.30.218:8010',
    'JF':'http://192.168.2.30:8010',
}

EMP_REST_API_USERNAME = 'hb'
EMP_REST_API_PASSWORD = 'hb11'

EMP_RESTAPI_ENDPOINT = {
    ##標準格式, method不寫時,默認為get exclude不寫時表示沒有哪個服務需要排除
    'get_allman':{'url':'/employee/get_allman','method':'get'}, 
}

SCHEDULE_SERVER= "http://192.168.2.92:8080/AppService"

#PMIS_REST_API_SERVER = "http://192.168.2.83:8014"  #用於排期的老版本的PMIS_Rest_Api
PMIS_REST_API_SERVER = "http://222.118.20.236:8054"  #用於排期的老版本的PMIS_Rest_Api
PMIS_REST_API_SERVER_NEW = "http://222.118.20.236:8054"
PMIS_REST_API_USERNAME = 'admin'
PMIS_REST_API_PASSWORD = 'sing11'
PMIS_RESTAPI_ENDPOINT = {
    ##標準格式, method不寫時,默認為get exclude不寫時表示沒有哪個服務需要排除
    'scenarioSchedule':{'url':'/schedule/scenarioSchedule/','method':'get'},
    'translate':{'url':'/ai/translate','method':'post'},
    'task_request_approve':{'url':'/task/api/task/{0}/request_approve/', 'method':"post"},
    'task_approve':{'url':'/task/api/task_approve/approve/','method':"post"},
    'task_reject':{'url':'/task/api/task_approve/reject/','method':"post"},
    'globalScheduleWithTask':{'url':"/schedule/globalScheduleWithTask", 'method':'post'},
    'synctaskissuedata':{'url':"/systembug/syncdata/", 'method':'post'}
}

NTFY_SERVER = "http://192.168.2.16:8810/"
NTFY_USERNAME = "pmis"
NTFY_PASSWORD = "pmis"

LangChain_SERVER = "http://183.63.205.83:8113"
WEBPMIS_SERVER = "http://222.118.20.236:8000/en"
#WEBPMIS_SERVER_OUT = "http://183.63.205.83:8000/en"
WEBPMIS_SERVER_OUT = "http://222.118.20.236:8052/en"

OPENAPI_KEY = "xxx"
OPENAPI_URL = "https://api.openai.com/v1/chat/completions"
#OPENAPI_PROXY_URL = "http://192.168.2.92:57837?type=http"
OPENAPI_PROXY_URL = "http://127.0.0.1:59527?type=http"
#OPENAPI_MODEL = "gpt-4-turbo-preview"
OPENAPI_MODEL = "gpt-4o"

SALC_SERVER = "http://183.63.205.83:8239"

AI_RESTAPI_SERVER = "http://222.118.20.236:8102"
AI_REST_API_USERNAME = 'admin'
AI_REST_API_PASSWORD = 'sing11'